CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE pozdrik (
    id_pozdr integer GENERATED BY DEFAULT AS IDENTITY,
    interest text,
    pozhelanie text,
    textpozdr text,
    CONSTRAINT pozdrik_pkey PRIMARY KEY (id_pozdr)
);

CREATE TABLE users (
    appid uuid NOT NULL DEFAULT (gen_random_uuid()),
    login text NOT NULL,
    password text NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (appid)
);

CREATE TABLE friend_list (
    appid uuid NOT NULL,
    friend_username text,
    friend_name text NOT NULL,
    date_birth date NOT NULL,
    id_pozdr integer,
    CONSTRAINT friend_list_appid_fkey FOREIGN KEY (appid) REFERENCES users (appid) ON DELETE CASCADE,
    CONSTRAINT friend_list_id_pozdr_fkey FOREIGN KEY (id_pozdr) REFERENCES pozdrik (id_pozdr) ON DELETE SET NULL
);

CREATE TABLE mail_comprehensions (
    appid uuid NOT NULL,
    mail text NOT NULL,
    CONSTRAINT mail_comprehensions_appid_fkey FOREIGN KEY (appid) REFERENCES users (appid) ON DELETE CASCADE
);

CREATE TABLE tg_comprehensions (
    appid uuid NOT NULL,
    tg_id bigint,
    CONSTRAINT tg_comprehensions_appid_fkey FOREIGN KEY (appid) REFERENCES users (appid) ON DELETE CASCADE
);

CREATE INDEX "IX_friend_list_appid" ON friend_list (appid);

CREATE INDEX "IX_friend_list_id_pozdr" ON friend_list (id_pozdr);

CREATE INDEX "IX_mail_comprehensions_appid" ON mail_comprehensions (appid);

CREATE UNIQUE INDEX mail_comprehensions_mail_key ON mail_comprehensions (mail);

CREATE INDEX "IX_tg_comprehensions_appid" ON tg_comprehensions (appid);

CREATE UNIQUE INDEX tg_comprehensions_tg_id_key ON tg_comprehensions (tg_id);

CREATE UNIQUE INDEX users_login_key ON users (login);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250311072225_Initial', '9.0.2');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250311073726_test', '9.0.2');

DROP INDEX "IX_friend_list_appid";

UPDATE friend_list SET friend_username = '' WHERE friend_username IS NULL;
ALTER TABLE friend_list ALTER COLUMN friend_username SET NOT NULL;
ALTER TABLE friend_list ALTER COLUMN friend_username SET DEFAULT '';

ALTER TABLE friend_list ADD CONSTRAINT friend_list_pkey PRIMARY KEY (appid, friend_username);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250311073826_add comb key for friend list', '9.0.2');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250311080656_add connsetionstring', '9.0.2');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250311101739_username not null', '9.0.2');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250312084034_testjenek', '9.0.2');

UPDATE friend_list SET id_pozdr = 0 WHERE id_pozdr IS NULL;
ALTER TABLE friend_list ALTER COLUMN id_pozdr SET NOT NULL;
ALTER TABLE friend_list ALTER COLUMN id_pozdr DROP DEFAULT;
ALTER TABLE friend_list ALTER COLUMN id_pozdr ADD GENERATED ALWAYS AS IDENTITY;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250312091100_chilia20', '9.0.2');

COMMIT;

