// <auto-generated />
using System;
using Infrastructure.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250311080656_add connsetionstring")]
    partial class addconnsetionstring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Models.FriendList", b =>
                {
                    b.Property<Guid>("Appid")
                        .HasColumnType("uuid")
                        .HasColumnName("appid");

                    b.Property<string>("FriendUsername")
                        .HasColumnType("text")
                        .HasColumnName("friend_username");

                    b.Property<DateOnly>("DateBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_birth");

                    b.Property<string>("FriendName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("friend_name");

                    b.Property<int?>("IdPozdr")
                        .HasColumnType("integer")
                        .HasColumnName("id_pozdr");

                    b.HasKey("Appid", "FriendUsername")
                        .HasName("friend_list_pkey");

                    b.HasIndex("IdPozdr");

                    b.ToTable("friend_list", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Models.MailComprehension", b =>
                {
                    b.Property<Guid>("Appid")
                        .HasColumnType("uuid")
                        .HasColumnName("appid");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mail");

                    b.HasIndex("Appid");

                    b.HasIndex(new[] { "Mail" }, "mail_comprehensions_mail_key")
                        .IsUnique();

                    b.ToTable("mail_comprehensions", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Models.Pozdrik", b =>
                {
                    b.Property<int>("IdPozdr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pozdr");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPozdr"));

                    b.Property<string>("Interest")
                        .HasColumnType("text")
                        .HasColumnName("interest");

                    b.Property<string>("Pozhelanie")
                        .HasColumnType("text")
                        .HasColumnName("pozhelanie");

                    b.Property<string>("Textpozdr")
                        .HasColumnType("text")
                        .HasColumnName("textpozdr");

                    b.HasKey("IdPozdr")
                        .HasName("pozdrik_pkey");

                    b.ToTable("pozdrik", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Models.TgComprehension", b =>
                {
                    b.Property<Guid>("Appid")
                        .HasColumnType("uuid")
                        .HasColumnName("appid");

                    b.Property<long?>("TgId")
                        .HasColumnType("bigint")
                        .HasColumnName("tg_id");

                    b.HasIndex("Appid");

                    b.HasIndex(new[] { "TgId" }, "tg_comprehensions_tg_id_key")
                        .IsUnique();

                    b.ToTable("tg_comprehensions", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Models.User", b =>
                {
                    b.Property<Guid>("Appid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("appid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Appid")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Login" }, "users_login_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Models.FriendList", b =>
                {
                    b.HasOne("Infrastructure.Models.User", "App")
                        .WithMany()
                        .HasForeignKey("Appid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("friend_list_appid_fkey");

                    b.HasOne("Infrastructure.Models.Pozdrik", "IdPozdrNavigation")
                        .WithMany()
                        .HasForeignKey("IdPozdr")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("friend_list_id_pozdr_fkey");

                    b.Navigation("App");

                    b.Navigation("IdPozdrNavigation");
                });

            modelBuilder.Entity("Infrastructure.Models.MailComprehension", b =>
                {
                    b.HasOne("Infrastructure.Models.User", "App")
                        .WithMany()
                        .HasForeignKey("Appid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mail_comprehensions_appid_fkey");

                    b.Navigation("App");
                });

            modelBuilder.Entity("Infrastructure.Models.TgComprehension", b =>
                {
                    b.HasOne("Infrastructure.Models.User", "App")
                        .WithMany()
                        .HasForeignKey("Appid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tg_comprehensions_appid_fkey");

                    b.Navigation("App");
                });
#pragma warning restore 612, 618
        }
    }
}
