@startuml
rectangle "прокси" as DBPROXY{ 
    rectangle "сущности" as Entities{
        rectangle "модель" as MODEL{
            rectangle "список друзей"  as Friendlit
            rectangle "связь appid - mail"  as MailC
            rectangle "связь appid - telegram"  as TgC
            rectangle "поздравление"  as Pozdrik
            rectangle "Аккаунты"  as Uers
        }
        rectangle "Щаблоны" as Templates{
            rectangle "шаблон для регистрации" as RegistTemp
            rectangle "шаблон для попдписи тг" as RegistTGTemp
            rectangle "шаблон для входа" as LoginTemnp
            rectangle "шаблон для проверка сущ" as CHExistTemp
            rectangle "шаблон для смены парол" as ChangePswTemp
            rectangle "шаблон - передача id" as AppidTemp
            rectangle "шаблон для add up" as ADDAndUpdateTemp
            rectangle "шаблон для del" as DeleteTemp
            
            
            
        }
    }
    rectangle "Уровень интерфейсов" as Aplication{
        rectangle "User" as IUser{
            rectangle CreateUser
            rectangle UpdateUser
            rectangle ExistUserCheck
        }
        
         rectangle "MailComp" as IMAILCOMP{
            rectangle ADDMAIL
            rectangle GETID
        }
        rectangle "TGComp" as ITGCOMP{
            rectangle ADDTG
            rectangle GETID
        }
        
         rectangle "Friendlist" as IFriendlist"{
            rectangle ADDFriend
            rectangle DELETEFriend
            rectangle UPDATEFriend
            rectangle SELECTFORappID
            rectangle GetIdPozdr
            rectangle GetTodayKents 
        }
        rectangle "Pozdrik" as IPozdrik"{
            rectangle AddIntrAndPozh
            rectangle SELECTPOZDR
        }
    }




    rectangle "апи" as API{
        rectangle "REGIST(LOGIN,PSW, email)" as REGISTR
        rectangle "REgistTg(APPID,tgid)" as RegistrTGID
        rectangle "LOGIN(LOGIN,PSW)" as LOGIN
        rectangle "ForgotPSWEXIST?(email)" as CheckEXIST
        rectangle "ForgotPswChange(appid,psw)" as ChangePsw
        
        rectangle "SELECT(APPID)" as SELECTAPPID
        rectangle "Update(APPID, FriendUsername, FriendName, DateB, Interest, Pozh)" as Update
        rectangle "ADD(APPID, FriendUsername, FriendName, DateB, Interest, Pozh)" as Add
        rectangle "ADD(APPID, FriendUsername)" as delete
      }
}


database "база данных" as db

@enduml